# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker

stages:
  - git_clone_refs
  - dwonload_rom
  - extract

image: tangcuyu/mipay-extracter-centos:latest

cache:
  paths:
    - $BUILD_DIR/*

get-mipay-extract:
  stage: git_clone_refs
  only:
    refs:
      - dev
#   cache:
#     paths:
#       - $BUILD_DIR
  script:
    - echo "git clone https://github.com/linusyang92/mipay-extract.git ..."
    # - bash ./shell-script/installation_dependency.sh
    - mkdir -p $BUILD_DIR
    - rm $BUILD_DIR/* -rf
    - git clone https://github.com/linusyang92/mipay-extract.git

dwonload-rom:
  stage: dwonload_rom
  only:
    refs:
      - dev
  script:
    - echo "download china-dev rom..."
    - pwd && ls -al
    - cd $BUILD_DIR && ls al && pwd
    - wget $CHINA_DEV_ROM_URL
    
extract-mipay:
  stage: extract
  only:
    refs:
      - dev
  script:
    - echo "extracting mipay..."
    - pwd && ls -al
    - mkdir -p $MIPAY_ZIP_DIR && ls -al && pwd
    - cd $BUILD_DIR && ls al && pwd
    - pwd && ./extract.sh
    - ls -al && cp $(ls | grep mipay-*.zip) ../$MIPAY_ZIP_DIR/ && ls -al

  artifacts:
    paths:
      - $MIPAY_ZIP_DIR/
