# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker

stages:
  - git_clone_refs
  - dwonload_rom
  - extract

image: tangcuyu/mipay-extracter-centos:latest

cache:
  paths:
    - $BUILD_DIR/*
    # - mipay-extract-master/
    # - master.zip

get-mipay-extract:
  stage: git_clone_refs
  only:
    refs:
      - dev

  script:
    - echo "git clone https://github.com/linusyang92/mipay-extract.git ..."
    - ls $BUILD_DIR || wget -c -nv --tries=40 -w 10 -T 10 --user-agent="Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Mobile Safari/537.36" https://github.com/linusyang92/mipay-extract/archive/master.zip || unzip master.zip
    - ls $BUILD_DIR || unzip master.zip || tree

dwonload-rom:
  stage: dwonload_rom
  only:
    refs:
      - dev
  script:
    - echo "download china-dev rom..."
    - pwd && ls -al
    - cd $BUILD_DIR && ls al && pwd
    - cd $BUILD_DIR && ls miui_*.zip || wget -c -nv --tries=40 -w 10 -T 10 --user-agent="Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Mobile Safari/537.36" "$CHINA_DEV_ROM_URL" || ls -al
    
extract-mipay:
  stage: extract
  only:
    refs:
      - dev
  cache:
    paths:
      - $MIPAY_ZIP_DIR/*
  script:
    - echo "extracting mipay..."
    - mkdir -p $MIPAY_ZIP_DIR && ls -al && pwd
    - cd $BUILD_DIR && ls -al && pwd
    - ls -al && pwd && ./extract.sh
    - ls -al && cp $(ls | grep mipay-*.zip) ../$MIPAY_ZIP_DIR/

  artifacts:
    paths:
      - $MIPAY_ZIP_DIR/
